name = "ODEInterfaceDiffEq"
uuid = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "3.12.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
Compat = "2.2, 3.0, 4"
DataStructures = "0.18"
DiffEqBase = "6.21"
FunctionWrappers = "1.0"
ODEInterface = "0.5"
Reexport = "0.2, 1.0"
SciMLBase = "1.73"
julia = "1.6"

[extras]
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ODEProblemLibrary"]
