name = "ODEInterfaceDiffEq"
uuid = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "v3.2.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"
